Create fab-files with a Makefile
jadonk/PocketBone pull request #15
Opened 2017-03-19 05:18 UTC by hzeller

Hi Jason,
In the context of the BeagleBone Blue reporting, I stumbled upon your Octavo-based PocketBone project. To make things simple to fab, I added a Makefile that creates a zip file with all of them.

Also, I personally like if the fabbed output contains a git hash and timestamp so that it is easy to find the right version when your desk is full of various stages of the project :). I think that can be useful here as well. So added that by adding a string on the back silk screen `%%gitversion%%` and a sed script in the Makefile that replaces that with the git log version of the pcb file.

(The standard Protel names for the inner layers are created with suffix *.g2 and *.g3. For some reason, OshPark does not recognize these but wants *.g2l and *.g3l. I opened a ticket with them as they promise that they understand the Protel names generated by KiCAD).

This requires, that the Python script extension for KiCAD are installed on the machine.

Cheers,
  Henner (the BeagleG guy).

o Add Python script that can generate fabbing files from the command …
o Add Makefile that makes use of it: just calling 'make' will create
  a zip file with the necessary layers.
o Send kicad_pcb through a sed script to change %%gitversion%% with
  the git hash and timestamp of the pcb file.
o Add a %%gitversion%% string on the back silkscreen, so that it
  is simple to identify the particular version of a fabbed board.

2017-03-22 21:29 UTC, jadonk requested changes
Please annotate the rest of the changes in the source files.

2017-03-22 21:29 UTC, jadonk commented on pocketbone-kicad.kicad_pcb
> +    (area 103.93175 93.91396 162.501581 132.574809)
Why is the board outline adjusted?

2017-03-22 21:29 UTC, jadonk commented on pocketbone-kicad.kicad_pcb
> +    (diff_pair_gap 0.25)
Looks handy. Is this a design rule check?

2017-03-22 21:29 UTC, jadonk commented on pocketbone-kicad.kicad_pcb
> +    (fp_text reference C2 (at 1.609 0.0508) (layer F.SilkS)
Lots of these. don't know if they are harmless.

2017-03-22 21:29 UTC, jadonk commented on pocketbone-kicad.kicad_pcb
> +  (gr_text %%gitversion%% (at 123.825 112.395 90) (layer B.SilkS) (tstamp 58CDFF39)
This seems to be the main point of the edit. likely needs to be isolated in the patch.

2017-03-22 21:29 UTC, jadonk commented on pocketbone-kicad.kicad_pcb
> +  (gr_text %%gitversion%% (at 123.825 112.395 90) (layer B.SilkS) (tstamp 58CDFF39)
BTW, I love the idea of the silkscreen indicating the PCB revision. Was that one of the main thrusts?

2017-03-23 11:43 UTC, hzeller commented
I think most of these changes are due to opening it with one version of kicad and saving it with another.
The changes all look benign: for instance 
```
  (fp_text reference C2 (at 1.609 0.0508 360) (layer F.SilkS)
```
turns something by 360 degrees, and the newer KiCad decided that this is the same as not turning it by zero degrees
```
   (fp_text reference C2 (at 1.609 0.0508) (layer F.SilkS)
```
There are other cases in which multiple of 360 degrees are normalized.

Anyway, if you want I can just manually add the text to the pcb file, so that the changes are minimal.

2017-03-23 12:21 UTC, hzeller commented
Alright, I have now updated the change by
  * Only including the one text addition in the PCB file needed for the %%gitversion%% string.
  * Updated the Python script to work reliably with OshPark (In the ticket they told me that it would work well if the edge file would be named `*Edge_Cuts*` instead of `*EdgeCuts*`.

The motivation for this change is not only the %%gitversion%% thing, but also that it is possible to have a one-stop way to create the gerber files from the raw files. It is very annoying to have to open a UI just to create gerber files. With the script, everything is already contained to make it work.

Since these are now three accumulated submits, I suggest to squash the pull request.

2017-03-23 22:44 UTC, hzeller commented on pocketbone-kicad.kicad_pcb
> +  (gr_text %%gitversion%% (at 123.825 112.395 90) (layer B.SilkS) (tstamp 58CDFF39)
This is now isolated, yep.

2017-03-25 12:13 UTC, jadonk commented
@mwelling I'm trying to keep this repo up-to-date. Do you also plan to merge this script? Shall I merge and create a pull request back to you?

2017-03-25 16:14 UTC, mwelling commented
@jadonk Since the pull request is on your repository, I think you should merge and I can pull the changes.

2017-03-28 02:26 UTC, hzeller commented
Is there anything else needed from me ?

2017-03-28 14:42 UTC, merged